config/routes.rb
Lrnews::Application.routes.draw do
  resources :users
  
  resources :sessions
  
  resources :infos do
    resources :comments do
      post "create_comment", :on => :collection
      post "reply", :on => :collection
    end
  end

  root :to => 'infos#index'
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :info
  attr_accessible :body, :from, :parent_id, :info_id
  validates :body, :from, presence: true
end

app/models/info.rb
class Info < ActiveRecord::Base
  attr_accessible :text, :title, :url, :user
  has_many :comments
  
  validates :title, :text, presence: true
  validates :title, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password, :password_confirmation
  validates :name, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def authenticate!
    redirect_to sessions_path unless current_user
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
         
  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate!, :only => [:create_comment, :show, :index]
  
  def index
    @info = Info.find(params[:info_id])
    @comment = Comment.new
    @comments = @info.comments.where(:parent_id => nil)
  end

  def create_comment
    @info = Info.find(params[:info_id])
    comment = Comment.new(params[:comment])
    @info.comments << comment
    @info.save
    redirect_to :back
  end

  def show
    @comments = Comment.find(params[:id])
    @comment = Comment.new
  end

  def reply
    @info = Info.find(params[:info_id])
    comment = Comment.new(params[:comment])
    @info.comments << comment
    @info.save
    redirect_to :info_comments
  end
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  before_filter :authenticate!, :only => [:new]
  # GET /infos
  # GET /infos.json
  def index
    @infos = Info.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @infos }
    end
  end

  # GET /infos/1
  # GET /infos/1.json
  def show
    @info = Info.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @info }
    end
  end

  # GET /infos/new
  # GET /infos/new.json
  def new
    @info = Info.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @info }
    end
  end

  # GET /infos/1/edit
  def edit
    @info = Info.find(params[:id])
  end

  # POST /infos
  # POST /infos.json
  def create
    @info = Info.new(params[:info])

    respond_to do |format|
      if @info.save
        format.html { redirect_to @info, notice: 'Info was successfully created.' }
        format.json { render json: @info, status: :created, location: @info }
      else
        format.html { render action: "new" }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /infos/1
  # PUT /infos/1.json
  def update
    @info = Info.find(params[:id])

    respond_to do |format|
      if @info.update_attributes(params[:info])
        format.html { redirect_to @info, notice: 'Info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /infos/1
  # DELETE /infos/1.json
  def destroy
    @info = Info.find(params[:id])
    @info.destroy

    respond_to do |format|
      format.html { redirect_to infos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
    render "new"
  end

  def create
    user = User.find_by_name params[:name]
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash.now.alert = "Invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<ul style="list-style:none">
  <li>
    <%= comment.from %> <%= comment.created_at.strftime("%Y-%m-%d %H:%M:%S") %><br />
    <%= comment.body %><br />
    <%= link_to "reply", "/infos/#{comment.info_id}/comments/#{comment.id}" %>
  </li>
  <% @comments = Comment.where("parent_id = ?", comment.id) %>
  <% if @comments %>
    <%= render :partial => "comment", :collection => @comments %>
  <% end %>
</ul>

app/views/comments/index.html.erb
<h4><%= @info.title %></h4>
<h5>created by <%= @info.user %> at <%= @info.created_at.strftime("%Y-%m-%d %H:%M:%S") %> |
 <%= @info.comments.count %> comments</h5>
<b>text</b><br />
<p><%= @info.text %></p>
<%= form_for @comment, :url => 'comments/create_comment', :method => :post do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this info from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if current_user %>
    <div class="field">
      <%= f.hidden_field :from, value: current_user.name %>
    </div>
  <% end %>
  <div class="field">
    <%= f.text_area :body, :size => "60x6" %>
  </div>
  <div>
    <%= f.hidden_field :info_id, :value => @info.id %>
  </div>
  <div class="actions" %>
    <%= f.submit :comment, class: "btn" %>
  </div>
<% end %>
<%= link_to "back", root_path %>
<%= render :partial => "comment", :collection => @comments %>

app/views/comments/show.html.erb
<table>
  <tr>
    <td>
      <%= @comments.from %>
    </td>
  </tr>
  <tr>
    <td>
      <%= @comments.created_at.strftime("%Y-%m-%d %H:%M:%S") %> |
      <%= link_to "parent", "/infos/#{@comments.info_id}/comments/#{@comments.parent_id}" %>
    </td>
  </tr>
  <tr>
    <td>
      <%= @comments.body %>
    </td>
  </tr>
  <tr>
  </tr>
</table>

<%= form_for @comment, :url => 'reply', :method => :post do |f| %>
  <div class="field">
    <%= f.text_area :body, :size => "60x6" %>
  </div>
  <div class="hidden">
    <%= f.hidden_field :parent_id, :value => @comments.id %>
    <%= f.hidden_field :info_id, :value => @comments.info_id %>
    <%= f.hidden_field :from, value: current_user.name %>
  </div>
  <div class="actions">
    <%= f.submit "reply" %>
  </div>
<% end %>

<% @comments = Comment.where("parent_id = ?", @comments.id) %>
<% if @comments %>
  <%= render :partial => "comment", :collection => @comments %>
<% end %>

app/views/infos/_form.html.erb
<%= form_for(@info) do |f| %>
  <% if @info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@info.errors.count, "error") %> prohibited this info from being saved:</h2>

      <ul>
      <% @info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form>
      <div>
        <label>
          <%= f.label :title %>
        </tlabel>
        <div>
          <%= f.text_field :title %>
        </div>
      </div>
      <div>
        <label>
          <%= f.label :url %>
        </label>
        <div>
          <%= f.text_field :url %>
        </div>
      </div>
      <div>
        <label>
          <%= f.label :text %>
        </label>
        <div>
          <%= f.text_area :text, rows: 6 %>
        </div>
      </div>
      <div>
        <div>
          <%= f.hidden_field :user, value: current_user.name %>
        </div>
      </div>
      <div>
        <div>
          <%= f.submit class: "btn"%>
        </div>
      </div>
  </form>
<% end %>

app/views/infos/comment.html.erb
<%= form_for @comment, :url => 'create_comment', :method => :post do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this info from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :from %><br />
    <%= f.text_field :from %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_field :body %>
  </div>
  <div>
    <%= f.hidden_field :parent_id, :value => @info.id %>
  </div>
  <div class="actions" %>
    <%= f.submit %>
  </div>
<% end %>
 <% @info.comments.each do |comment| %>
   <div>
     <p><%= comment.from %>さん:</p><br />
     <p><%= comment.body %><p><br />
   </div>
<% end %>

app/views/infos/edit.html.erb
<h1>Editing info</h1>

<%= render 'form' %>

<%= link_to 'Show', @info %> |
<%= link_to 'Back', infos_path %>

app/views/infos/index.html.erb
<% @infos.each do |info| %>
  <tr>
    <td>
      <%= info.id %>
    </td>
    <% if info.url.size > 0  %>
      <td>
        <%= link_to info.title, info.url %>
      </td>
      <span>(<%= info.url %>)</span>
    <% else %>
      <td>
        <%= link_to info.title, "/infos/#{info.id}/comments" %>
      </td>
    <% end %>
    <td>
      <%= link_to 'discuss', "/infos/#{info.id}/comments" %>
    </td>
  </tr>
  </br>
<% end %>

app/views/infos/new.html.erb
<h4>New info</h4>

<%= render 'form' %>

<%= link_to 'Back', infos_path %>

app/views/infos/show.html.erb
<p id="notice"><%= notice %></p>
<p class="lead">
  <%= @info.title %>
</p>
<p>
  <b>text:</b>
  <%= @info.text %>
</p>


<%= link_to 'Edit', edit_info_path(@info) %> |
<%= link_to 'Back', infos_path %>

app/views/layouts/_navigation.html.erb
<%= link_to "Lrnews", root_path, :class => 'brand' %>
<ul class="nav">
  <li>
  <%= link_to 'create', "/infos/new" %>
  </li>
  <% if current_user %>
    <li>
    <%= link_to 'Logout', "/sessions/#{current_user.id}",
      :confirm => 'are you sure?', :method => :delete %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', "/sessions" %>
    </li>
  <% end %>
  <% if current_user %>
    <li>
    <%= link_to 'Edit account', "/users/#{current_user.id}/edit" %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Sign up', "/users/new"  %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lrnews</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
  <body>
  <header class="navbar navbar-fixed-top">
    <nav class="navbar-inner">
      <div class="container">
        <%= render 'layouts/navigation' %>
      </div>
    </nav>
  </header>
  <div id="main" role="main">
    <div class="container">
      <div class="content">
        <div class="row">
          <div class="span12">

          <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </div>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> 
        prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <form>
      <div>
        <label>
          <%= f.label :name %>
        </label>
        <div>
          <%= f.text_field :name, size: 40 %>
        </div>
      </div>
      <div>
        <label>
          <%= f.label :password, 'password' %>
        </label>
        <div>
          <%= f.password_field :password, size: 40 %>
        </div>
      </div>
      <div>
        <label>
          <%= f.label :password_confirmation, 'password check' %>
        </label>
        <div>
          <%= f.password_field :password_confirmation, size: 40 %>
        </div>
      </div> 
      <div>
        <div>
          <%= f.submit :Create, class: "btn" %>
        </div>
      </div>
  </form>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Password digest</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.password_digest %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h4>New user</h4>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Password digest:</b>
  <%= @user.password_digest %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>